V1 unit tests
Squashed commit of the following:

commit 6f8c718742ce37091c5d9b2146c5e025af04fb3c
Author: Nicholas Rader <nick.rader@yahoo.com>
Date:   Thu Jun 29 01:44:25 2023 -0600

    gtest framework applied, minimal and basic currently

commit 5ef0bdd9c32a44a8eba7c233bbd549ae15169a38
Author: Nicholas Rader <nick.rader@yahoo.com>
Date:   Thu Jun 29 01:25:28 2023 -0600

    RED:  Wait, wut?  I fail on purpose, good red.

commit 2ffb6a56a896b6e572a4ebfb055b78b00e5fab6d
Author: Nicholas Rader <nick.rader@yahoo.com>
Date:   Wed Jun 28 23:01:06 2023 -0600

    I think remaing folder helped.  Didn't get 'gtest folder already exists' message in MSVS this time.  I did also build solution fully, first thing, but will try again on lookout for pop-ups

commit 59667bee38714c681350e680665315dff2c0de7f
Author: Nicholas Rader <nick.rader@yahoo.com>
Date:   Wed Jun 28 22:56:24 2023 -0600

    I can build on cli: 	cmake --build build/
    but for some reason, gtestd.lib fails to be built when building solution in MSVS.

    IDK?  Come back to this.  Lets confirm we can test things.

commit 499b1dd1b74fc5a8e4261a0bad87b4e0c1396ded
Author: Nicholas Rader <nick.rader@yahoo.com>
Date:   Wed Jun 28 19:16:49 2023 -0600

    WIP:  Yellow:  It built, but didn't quite go as planned.  We can work this out (speaking to the mouse in my pocket)

    Trying to build Gtest is MSVS:
    RED:
    LINK : fatal error LNK1104: cannot open file '..\bin\gtestd.lib'

    build/bin/: we have gtest_maind.lib, not gtestd.lib ... So there is a naming/configuration problem here, probably

    building using cmake not MSVS gives me an executable,  so just a problem with MSVS atm

commit 7d3318f73f6b0c0413c4f63b49e82f6e3e4566ee
Author: Nicholas Rader <nick.rader@yahoo.com>
Date:   Wed Jun 28 19:06:41 2023 -0600

    Try #2

commit b4bb231a8bd8dc2f36821add1fa1c5748d3d39c9
Author: Nicholas Rader <nick.rader@yahoo.com>
Date:   Wed Jun 28 18:51:12 2023 -0600

    Fingers Crossed:  Lets rebuild this project (remove build dir) and see if we got lucky?

commit 2ae9e91d055dfc088e0111d8dd6da7edc534e615
Author: Nicholas Rader <nick.rader@yahoo.com>
Date:   Wed Jun 28 18:30:21 2023 -0600

    1st pass on .cmake, need to add more stuff.  I have examples in other personal project

commit 25b985fed9be09f5b9e47206dd6f794101b4a1e9
Author: Nicholas Rader <nick.rader@yahoo.com>
Date:   Wed Jun 28 17:57:58 2023 -0600

    Initial Revision of project level CMakeLists.txt

Added test_fixture and more links to relevant 'how-to' from Gtest docs.

wip stash

forgot to add changes to index

Fixed case on UnitTests to unit_tests ; to be consistent with other naming

wamer

Fail up?  Now failing googletestverification, so idk... break time.

warmer, it compiles at least

GREEN: kind of.  Not sure if this is way to do it.  When peicemeal, fails for the two values not being passed in by GetParam()...  FFS, at least it compiles and give me results.  LOL.

V1 unittests.  Param isn't most useful presently.  However, illustrates for our purpose better than tutorial, imo.

wip

start attempt gMock

reinstate anonymous namespace

fixed linking of gmock_main in CMakelists.txt

Failing up.  Letss goooo.

GREEN: const needed to be included in parameters.

wip

 cmake updates

V1 gtest framework applied, minimal and basic currently

Squashed commit of the following:

commit 6f8c718742ce37091c5d9b2146c5e025af04fb3c
Author: Nicholas Rader <nick.rader@yahoo.com>
Date:   Thu Jun 29 01:44:25 2023 -0600

    gtest framework applied, minimal and basic currently

commit 5ef0bdd9c32a44a8eba7c233bbd549ae15169a38
Author: Nicholas Rader <nick.rader@yahoo.com>
Date:   Thu Jun 29 01:25:28 2023 -0600

    RED:  Wait, wut?  I fail on purpose, good red.

commit 2ffb6a56a896b6e572a4ebfb055b78b00e5fab6d
Author: Nicholas Rader <nick.rader@yahoo.com>
Date:   Wed Jun 28 23:01:06 2023 -0600

    I think remaing folder helped.  Didn't get 'gtest folder already exists' message in MSVS this time.  I did also build solution fully, first thing, but will try again on lookout for pop-ups

commit 59667bee38714c681350e680665315dff2c0de7f
Author: Nicholas Rader <nick.rader@yahoo.com>
Date:   Wed Jun 28 22:56:24 2023 -0600

    I can build on cli: 	cmake --build build/
    but for some reason, gtestd.lib fails to be built when building solution in MSVS.

    IDK?  Come back to this.  Lets confirm we can test things.

commit 499b1dd1b74fc5a8e4261a0bad87b4e0c1396ded
Author: Nicholas Rader <nick.rader@yahoo.com>
Date:   Wed Jun 28 19:16:49 2023 -0600

    WIP:  Yellow:  It built, but didn't quite go as planned.  We can work this out (speaking to the mouse in my pocket)

    Trying to build Gtest is MSVS:
    RED:
    LINK : fatal error LNK1104: cannot open file '..\bin\gtestd.lib'

    build/bin/: we have gtest_maind.lib, not gtestd.lib ... So there is a naming/configuration problem here, probably

    building using cmake not MSVS gives me an executable,  so just a problem with MSVS atm

commit 7d3318f73f6b0c0413c4f63b49e82f6e3e4566ee
Author: Nicholas Rader <nick.rader@yahoo.com>
Date:   Wed Jun 28 19:06:41 2023 -0600

    Try #2

commit b4bb231a8bd8dc2f36821add1fa1c5748d3d39c9
Author: Nicholas Rader <nick.rader@yahoo.com>
Date:   Wed Jun 28 18:51:12 2023 -0600

    Fingers Crossed:  Lets rebuild this project (remove build dir) and see if we got lucky?

commit 2ae9e91d055dfc088e0111d8dd6da7edc534e615
Author: Nicholas Rader <nick.rader@yahoo.com>
Date:   Wed Jun 28 18:30:21 2023 -0600

    1st pass on .cmake, need to add more stuff.  I have examples in other personal project

commit 25b985fed9be09f5b9e47206dd6f794101b4a1e9
Author: Nicholas Rader <nick.rader@yahoo.com>
Date:   Wed Jun 28 17:57:58 2023 -0600

    Initial Revision of project level CMakeLists.txt

Added test_fixture and more links to relevant 'how-to' from Gtest docs.

wip stash

forgot to add changes to index

Fixed case on UnitTests to unit_tests ; to be consistent with other naming

wamer

Fail up?  Now failing googletestverification, so idk... break time.

warmer, it compiles at least

GREEN: kind of.  Not sure if this is way to do it.  When peicemeal, fails for the two values not being passed in by GetParam()...  FFS, at least it compiles and give me results.  LOL.

V1 unittests.  Param isn't most useful presently.  However, illustrates for our purpose better than tutorial, imo.

wip

start attempt gMock

reinstate anonymous namespace

fixed linking of gmock_main in CMakelists.txt

Failing up.  Letss goooo.

GREEN: const needed to be included in parameters.

wip

 cmake updates

4. Exercise some code that uses the mocks; optionally, check the result using googletest assertions. If a mock method is called more than expected or with wrong arguments, you’ll get an error immediately.

wip: not sure class need be interface, just wrapped in interface?

What I was afraid of.  Using an already interface, meanse we MUST overrride ALL defined methods...
Letus try wrapping that MoFo.

GREEN:  So we can use the Interfaces directly...  However, then we must define ALL members...
If we use wrapper, can pick and choose our members at will.

YELLOW:  Complies, but both 'true' and 'false' pass test...  Without either, still pass test...

wip

GREEN:  We have Mocks working.  Yay!

re-formatted

wip; onto TypedTests example

wip: perhaps  unit* over tag..

wip

GREEN: wip, start Type-Parameterized

red: wip

GREEN: Dirty example while listening to Dirty South...

make more SC2 based names

red: DaUnit not defined.

GREEN: decalre unit

red: assert fails, tested = 0

green: this feels repetetive, keep looking more automated way. ... Perhaps incorporate

red: Severity Code Description Project File Line Suppression State Details
Error C2678 binary '!': no operator found which takes a left-hand operand of type 'sc2::IsUnit' (or there is no acceptable conversion) unit_tests_sample C:\Users\VonRansak\Bots\cpp-sc2\build\unit_tests_sample\test_unit_filters.cpp 16

red: assert_false not happy with !sc2::Unit

green: functors were not working for me.  I think I do better now.  Play around a bit.

green: I guess I got it staightened out.  I'm creating the struct of the unittypes I want to check.  The functor then allows me to call it with arguments, like type or unit.

green: making progress.

wip

error attempt to reference deleted function

wip

RED: Test Fixture is not a fan of our attempt to use the filters.  .. Seems like I SHOULD use a test fixture, but if it don't cooperate soon...

GREEN: seems need to add default ctor to sc3_unit_filters, for it to work right with test_fixtures in gtest

GREEN: Copy ctor not needed, for test_f ; but need to define a default ctor, confirmed.

yellow: idfk.  Take a look again, tomorrow.

ABANDON test fixture for functors, something happens I do not understand.  Simple tests works.

wip

cleanup

wip

wip, skeleton

GREEN: todo: flesh out and cover all cases.

formatting

formatting, cleanup

GREEN: Seems like a lot of duplication, but I can't figure a better way ATM.  The class nature of the fixtures and such is presenting me problems using the function objects.

wip,

GREEN: wip

wip

green: wip

GREEN: wip

GREEN: Version #1

cleanup

V1

DO NOT add files through Visual Studio... Put them in build folder, not project folder.

wip

latest wip

wip CI

trying to get api back to stock enough.  seemss I inserted a constructor

wip

wip

wip

Pull the thread.  function objects errors with test fixture.

wip

wip

wip, move unit_tests into tests

wip: red: redo cmakelists

GREEN: moved stuff around

wip

wip

formatting

wip: ci.yml

wip

Test it!!!  gogo

KISS

try this.

initialize empty unit.mineral contents, caused test error.

initialize values tested.  Mabye should be done in constructor?  Not sure if blizz had reason for not doing so?

what is it's value?

try this

Duh moment, initialized minerals not vespene.  Seems windows debugger was probably initializing to 0

caching attempt kiss method

copy from docs

wip

wip

wip

remove batch file

clang-format-buffer test_unit_filters.cpp

lint unit_tests

alskdf

 lksjf

a;lksd

la tee dah.

 lalal

move set below project()

lakjd

laalalala